Database new
CSC207-2022F-UofT/course-project-t_t pull request #58
Opened 2022-12-06 21:35 UTC by daybigh

Very significant changes to database & friendslist class,
-We now have a dedicated database using mongodb
-Friendslist class has been changed to Relations class 
-Relations class no longer keeps track of array of users and instead keeps track of array of refereces to users 
-tests cases have been edited to match the refactoring of databases & Relations class
-added gateway directory to keep seperate the database and usecases 
-many methods in pages which use Friendslistmanager have been refactored

2022-12-06 21:37 UTC, naraeleee approved these changes

2022-12-06 21:48 UTC, oshley213 requested changes
There should be some changes in RelationsManager and RelationsManagerTest since there were some changes made in Tina's latest branch (see the Tina's pr regarding FriendListManager and FriendListManagerTest that has not been merged yet). But other than that, it looks great. Hope it works.

2022-12-06 22:20 UTC, daybigh commented
@oshley213 Are you referring to the sort methods and tests for friendslist and blockedlist? It was an intentional choice to not implement those changes because I didn't think they affected how the software functioned. Are these methods required somwhere? or were you referring to something else in Tina's pr?

2022-12-06 22:32 UTC, naraeleee approved these changes, later dismissed

2022-12-06 22:34 UTC, thk421 approved these changes, later dismissed

2022-12-06 23:11 UTC, great-prophet approved these changes, later dismissed

2022-12-07 00:03 UTC, oshley213 submitted a review, later dismissed

2022-12-07 03:15 UTC, clarencechau approved these changes, later dismissed

2022-12-08 04:54 UTC, closed without merging